version: '2.1'

services:
  tvams-grp:
    image: template
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:80
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js
